# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - keyword-analysis

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://viridiumcontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_518690e1c8fb46a583c39c11694436f8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_44e6938b6fe14775a1bbb4c25f74d923 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: viridiumcontainerregistry.azurecr.io/keyword-analysis/v0.1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'keyword-analysis'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_84b402aac2b74d4ba82e6701d3db5e3e }}
        images: 'viridiumcontainerregistry.azurecr.io/keyword-analysis/v0.1:${{ github.sha }}'
